// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCv-0H9i7QnSFb2zp_38-KYCsQBuHm46RM',
    appId: '1:468266778105:web:1fded7bec13762ccec9128',
    messagingSenderId: '468266778105',
    projectId: 'ts-express-rest-api-example',
    authDomain: 'ts-express-rest-api-example.firebaseapp.com',
    storageBucket: 'ts-express-rest-api-example.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrrmCCsNSdi2IaRVEAf9-ZzsboPVvfvaM',
    appId: '1:468266778105:android:061abd94b6234d88ec9128',
    messagingSenderId: '468266778105',
    projectId: 'ts-express-rest-api-example',
    storageBucket: 'ts-express-rest-api-example.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB3Na4IgOYNfe2dZQjcQblJPwEx_hlwHE',
    appId: '1:468266778105:ios:b224029126bf8df0ec9128',
    messagingSenderId: '468266778105',
    projectId: 'ts-express-rest-api-example',
    storageBucket: 'ts-express-rest-api-example.appspot.com',
    iosBundleId: 'com.example.flutterTemplate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBB3Na4IgOYNfe2dZQjcQblJPwEx_hlwHE',
    appId: '1:468266778105:ios:ab1b181dd89dad68ec9128',
    messagingSenderId: '468266778105',
    projectId: 'ts-express-rest-api-example',
    storageBucket: 'ts-express-rest-api-example.appspot.com',
    iosBundleId: 'com.example.flutterTemplate.RunnerTests',
  );
}
